In [1]:
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences


data_1 = np.array(["kelime8 kelime2 kelime3", "kelime4 kelime5 kelime6 kelime7", 
                   "kelime8 kelime2 kelime3 kelime8"])
data_2 = np.array(["kelime1 kelime8 kelime8 kelime6", "kelime7 kelime8 kelime9 kelime5 kelime6"])

MAX_NUM_WORDS = 4
MAX_SEQUENCE_LENGTH = 8

/anaconda3/envs/py27dl/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [10]:
print "data_1:"
for cumle in data_1:
    print cumle
    
print "\ndata_2:"
for cumle in data_2:
    print cumle

data_1:
kelime8 kelime2 kelime3
kelime4 kelime5 kelime6 kelime7
kelime8 kelime2 kelime3 kelime8

data_2:
kelime1 kelime8 kelime8 kelime6
kelime7 kelime8 kelime9 kelime5 kelime6


In [14]:
tokenizer1 = Tokenizer(num_words=MAX_NUM_WORDS)
tokenizer1.fit_on_texts(data_1)
tokenizer2 = Tokenizer(num_words=MAX_NUM_WORDS)
tokenizer2.fit_on_texts(data_2)
print(tokenizer1.word_index)
print("- - - - - - - - -- - - - - - -")
print(tokenizer1.word_counts)
print("\n # # # # # # # # # # # # # # # \n")
print(tokenizer2.word_index)
print("- - - - - - - - -- - - - - - -")
print(tokenizer2.word_counts)

{'kelime2': 2, 'kelime3': 3, 'kelime6': 6, 'kelime7': 7, 'kelime4': 4, 'kelime5': 5, 'kelime8': 1}
- - - - - - - - -- - - - - - -
OrderedDict([('kelime8', 3), ('kelime2', 2), ('kelime3', 2), ('kelime4', 1), ('kelime5', 1), ('kelime6', 1), ('kelime7', 1)])

 # # # # # # # # # # # # # # # 

{'kelime1': 3, 'kelime6': 2, 'kelime7': 4, 'kelime5': 6, 'kelime8': 1, 'kelime9': 5}
- - - - - - - - -- - - - - - -
OrderedDict([('kelime1', 1), ('kelime8', 3), ('kelime6', 2), ('kelime7', 1), ('kelime9', 1), ('kelime5', 1)])


In [5]:
for item in tokenizer2.word_counts:
    print(item)

kelime2
kelime8
kelime6
kelime7
kelime9
kelime5


In [15]:
import collections
most_common1 = collections.Counter(tokenizer1.word_counts).most_common(MAX_NUM_WORDS)
most_common2 = collections.Counter(tokenizer2.word_counts).most_common(MAX_NUM_WORDS)
print(most_common1)
print(most_common2)

[('kelime8', 3), ('kelime2', 2), ('kelime3', 2), ('kelime6', 1)]
[('kelime8', 3), ('kelime6', 2), ('kelime1', 1), ('kelime7', 1)]


In [16]:
#tekrar etmeyecek şekilde birleştirme işlemi
a = set()
for i,k in most_common1:
    a.add(i)
for i,k in most_common2:
    a.add(i)

In [17]:
print a

set(['kelime2', 'kelime3', 'kelime1', 'kelime6', 'kelime7', 'kelime8'])


In [19]:
tokenizer3 = Tokenizer(num_words = 2*MAX_NUM_WORDS)
tokenizer3.fit_on_texts(a)
sequences1 = tokenizer3.texts_to_sequences(data_1)
sequences2 = tokenizer3.texts_to_sequences(data_2)
print(sequences1)
print(sequences2)

[[6, 1, 2], [4, 5], [6, 1, 2, 6]]
[[3, 6, 6, 4], [5, 6, 4]]


In [20]:
tokenizer3.word_index

{'kelime1': 3,
 'kelime2': 1,
 'kelime3': 2,
 'kelime6': 4,
 'kelime7': 5,
 'kelime8': 6}

In [21]:
x_train1 = pad_sequences(sequences1, maxlen=MAX_SEQUENCE_LENGTH)
print(x_train1)

[[0 0 0 0 0 6 1 2]
 [0 0 0 0 0 0 4 5]
 [0 0 0 0 6 1 2 6]]


In [22]:
x_train2 = pad_sequences(sequences2, maxlen=MAX_SEQUENCE_LENGTH)
print(x_train2)

[[0 0 0 0 3 6 6 4]
 [0 0 0 0 0 5 6 4]]
